### ISSUE TITLE
v9-gui: "Nodes" issues (keep it open until the list is empty)

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4166]
- [x] after apply new role to nodes, list isn't refreshed #4143
- [x] Confusing selection from Nodes module #4144

# Search
- [x] Missing search options: `Status`,`Source Switch Port`, `Source Switch Port Description`, `Security Event Name`
- [x] Unexpect character (`[?]`) in dropdown search menu for `Bypass VLAN`, `Connection type` and `Device manufacturer` items
- [x] Default view for Search menu contains extra columns: `IPv6 address`, `Device Type`
- [ ] `Tenant` column contain integer (1) in place of string (default)
- [ ]  `Tenant` is the first column before `Status`
![Screenshot from 2019-04-12 15-56-49](https://user-images.githubusercontent.com/10830260/56042826-3deeec80-5d3c-11e9-93d0-c8ec9f9bc257.png)

- [x] `Owner` field is not clickable
- [ ] Missing icon when `SSID` field contain a value
![Screenshot from 2019-04-01 14-43-51](https://user-images.githubusercontent.com/10830260/55328450-a9a79e80-548c-11e9-914d-9a75b323cf0e.png)
- [x] `Datetime Detected, Registered, Unregistered` search options should be replace by `Detected Date`, `Registration Date` and `Unregistration Date` to be consistent with columns name.
- [x] `Online/Offline` display a `online` value in place of `on` in old GUI
- [ ] Background color for `Status` column and `online` keyword are different between old and new GUI
- [x] Missing columns `Switch Port`, `Switch Port Description` and `Switch Description` 
- [x] Advanced search: missing block to filter on time ranges (Online between, Detected between)
- [ ] Wrond display for search options: `Security Event Open Count` #3400 and `Security Event Close Count` #3400
- [x] Left panel: Switch Groups menu and sub-menus are on same level
![Screenshot from 2019-04-04 11-00-19](https://user-images.githubusercontent.com/10830260/55543206-dcd67180-56c8-11e9-881e-40375688c7e4.png)

# View
- [x] Voice Over IP field has been replace by VOIP
- [x] Missing seconds in specific timestamps:
![Screenshot from 2019-04-01 15-46-01](https://user-images.githubusercontent.com/10830260/55332256-4ff7a200-5495-11e9-9186-616cdcfd78ce.png)
- [x] REEVAULATE should be REEVALUATE
- [x] `Device Manufacturer` is missing from `Fingerbank` tab
- [x] `DHCP Vendor` is not displayed in `Fingerbank` tab
- [ ] `IPv4` tab: date format is different between old GUI and new GUI 
- [x] `REEVALUATE ACCESS`, `REFRESH FINGERBANK` and `RESTART SWITCHPORT` are not available on all tabs (Edit, Fingerbank and Location)
- [x] `RESTART SWITCHPORT` button is not clickable
- [x] Display a message when there is no data to display for a tab, in old GUI, we had "No security event found"
- [x] Alignment of bottom borders is not perfect on `Location` tab
![Screenshot from 2019-04-04 10-16-17](https://user-images.githubusercontent.com/10830260/55540446-4a7f9f00-56c3-11e9-979c-2bed60aadd1c.png)
- [ ] Different layout and options for `Option82` tab
- [ ] `Option82` tab: date format is different between old GUI and new GUI 
- [ ] Missing `Rapid7` tab

# Create
- [x] Creating a node manually fails #4137
- [x] Displaying a new node created with only a MAC failed (`"t.node.fingerbank is undefined"` in console)

# Import
- [ ] Node CSV import new line handling (#4180)
- [x] nodes import from CSV - missing import options #4136

**Comment by nqb** [comment]
TODO:
- [ ] Security events

**Comment by satkunas** [comment]
> Tenant column contain integer (1) in place of string (default)

It's an integer column

**Comment by satkunas** [comment]
> Missing icon when SSID field contain a value

Not reliable. If the user doesn't select `SSID` as a visible column, then the data isn't available to show/hide the icon. If they do enable the column then there's no need for the icon. There are workarounds, but let's see if we can get away without it - unless there are objections.

**Comment by satkunas** [comment]
> Background color for Status column and online keyword are different between old and new GUI

I don't see online/offline colors currently. Can you please detail the difference, so I don't need to push a static locationlog entry :)

**Comment by satkunas** [comment]
> IPv4 tab: date format is different between old GUI and new GUI

> Option82 tab: date format is different between old GUI and new GUI

This looks like an intentional locale change by @cgx

**Comment by satkunas** [comment]
> REEVALUATE ACCESS, REFRESH FINGERBANK and RESTART SWITCHPORT are not available on all tabs (Edit, Fingerbank and Location)

This is intentional. I tried to put them with the tab that fit their context. It's too cluttered when included on ea. tab.

**Comment by satkunas** [comment]
> RESTART SWITCHPORT button is not clickable

There's now a check to determine if the button will do anything. It's disabled if there's no purpose. Here's the logic behind this:
```javascript
    canReevaluateAccess (node) {
      return (node.locations && node.locations.length > 0 && ((node.ip4 && node.ip4.ip) || (node.ip6 && node.ip6.ip)))
    },
    canRestartSwitchport (node) {
      return (node.locations && node.locations.filter(node =>
        node.end_time === '0000-00-00 00:00:00' && // require zero end_time
        network.connectionTypeToAttributes(node.connection_type).isWired // require 'Wired'
      ).length > 0)
    },
```

**Comment by satkunas** [comment]
> Displaying a new node created with only a MAC failed ("t.node.fingerbank is undefined" in console)

Unable to reproduce

**Comment by satkunas** [comment]
All issues address or moved to #4257

**Comment by nqb** [comment]
> If they do enable the column then there's no need for the icon

It's a common way to identify wireless users
