### ISSUE TITLE
v9-gui: "Users" issues (keep it open until the list is empty)

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4167]
- [x] Missing actions button from Users page #4138

# Search

# View
- [x] Missing `Psk` and `lang` field
- [x] Missing `Devices` and `Security Events` tab

# Create
- [x] Password must be at least 6 characters, no such limitation in old GUI
- [x] Access Level drop-down doesn't display all choices (missing: NONE, ALL, ALL_PF_ONLY) (see #3646)
- [x] Multiple users creation doesn't work (see #4256)
- [X] (consolidated) Printable passwords page is missing when creating or importing multiple users
- [x] After creating a user, web browser stay on creation page without cleaning "Username" field. Consequently, it displays: "Username exists".
- [x] Creating a user with a password doesn't create entry in `password` table (not the case through API)
- [x] We can create a user without Registration Windows (not the case in old GUI)
- [x] Setting access level is not possible
![Screenshot from 2019-04-25 09-44-52](https://user-images.githubusercontent.com/10830260/56718369-e474bd80-673e-11e9-839d-21eb63d0fa05.png)

# Import

**Comment by satkunas** [comment]
Remainder moved to #4257

**Comment by nqb** [comment]
@satkunas:

> - [x] Password must be at least 6 characters, no such limitation in old GUI

Still presents in latest builds.

**Comment by nqb** [comment]
@satkunas: I updated this issue with new bugs

**Comment by nqb** [comment]
@cgx, I reopened this issue because:

Password must be at least 6 characters, no such limitation in old GUI

has not been fixed.

Let me know if you want another way to manage this issue.

**Comment by cgx** [comment]
I propose to keep this requirement and eventually make it a configuration parameter.

**Comment by nqb** [comment]
Ok.
