### ISSUE TITLE
v9-gui: Consolidated Issues

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#4257]
I've moved multiple outstanding issues here, to consolidate them in one place. I will leave a link to the original issue and close them.

**Invalid or Missing Meta** (for @jrouzierinverse)
- [x] Users -> Create: Access Level drop-down doesn't display all choices (missing: NONE, ALL, ALL_PF_ONLY) (see #3646, from #4167)
- [x] Realms View -> RADIUS ACCT still empty even if there is some radius authentication sources defined. (from #4151)
- [x] Authentication sources -> AD/LDAP : Scope subtree by default (or list empty undefined) (from #4151)
- [x] Authentication sources -> No choice for Access duration (from #4151)
- [x] Authentication sources -> AD/LDAP : Encryption None by default (or list empty undefined) (from #4151)
- [x] Authentication sources -> Email : Email activation Timeout set 10 minutes by default (see #4323, from #4151)
- [x] Authentication sources -> Sponsor: Sponsor Validation should be enabled (from #4151)
- [x] Switches -> SNMP version list is empty and should be v2c by default (from #4151)
- [x] Switches -> SNMP predefined field are missing (Community read: public) (from #4151)
- [x] Connection profiles -> Enable profile should be enabled by default (from #4151)
- [x] Connection profiles -> Missing default values (from #4151)
- [x] Integration -> Firewall SSO: Missing "$pf_username" default value for "Username format" (from #4153)
- [x] Integration -> Firewall SSO: Missing default port for Barracuda NG

**Missing/Broken Search**
- [x] Integration -> Firewall SSO: Search does not work (from #4153)
- [x] Integration -> Syslog Parsers: Search does not work (from #4153)
- [x] Integration -> Syslog Forwarding: Search does not work (from #4153)
- [x] Integration -> WRIX: Missing filtering options on all criteria (Id, Location identifier, etc.) (from #4153)

**Back End Bugs** (@jrouzierinverse )
- [x] Wrond display for search options: Security Event Open Count (#3400) and Security Event Close Count (#3400) (from #4166)
- [x] Device Registration -> Cannot delete the previous device registration created in the alt GUI in the old GUI (from #4160) (see https://github.com/inverse-inc/packetfence/issues/4160#issuecomment-480860900)
- [x] Authentication sources -> Email/Sponsor : Error when saving: ERROR pfperl-api(7770): HFH: param clash for email_activation_timeout.interval (from #4151)
- [x] Authentication sources -> Eduroam on create: ERROR pfperl-api(30838): Attribute (local_realm) does not pass the type constraint because: Validation failed for 'ArrayRef[Str]' with value "" at constructor pf::Authentication::Source::EduroamSource::new (defined at /usr/local/pf/lib/pf/Authentication/Source/EduroamSource.pm line 121) line 89 (from #4151)
- [x] Authentication sources -> Authorized.net on create: ERROR pfperl-api(30836): Attribute (transaction_key) is required at /usr/lib/x86_64-linux-gnu/perl5/5.24/Moose/Object.pm line 24 (from #4151)
- [x] Authentication sources -> Paypal on create: ERROR pfperl-api(30836): Attribute (cert_id) is required at /usr/lib/x86_64-linux-gnu/perl5/5.24/Moose/Object.pm line 24 (from #4151)
- [x] Authentication sources -> Stripe on create: ERROR pfperl-api(30838): Attribute (publishable_key) is required at /usr/lib/x86_64-linux-gnu/perl5/5.24/Moose/Object.pm line 24 (from #4151)
- [x] Connection profiles -> Locale required when we try to add one (from #4151)
- [x] Roles -> Discrepancy in *Map values (uses "Y", "N", "1" and "0") (from #4126)
- [x] Sources/Billing/Provisioners/Scanners form issue, the field should only accept one value (sms should not be allowed in the example)
![image](https://user-images.githubusercontent.com/1553962/57051981-3b542880-6c52-11e9-8ea7-ec34edb0afb5.png)

**Front End Bugs**
- [x] Device Registration -> Cannot add OS in the new device registration tab (from #4160)
- [x] Node CSV import new line handling (#4180) (from #4166)
- [x] PKI Providers -> Cannot add OS in the provisioner tab (from #4160)
- [x] PKI Providers -> The locality list is empty in the SCEP PKI option in the PKI provider tab (from #4160)
- [x] Cannot reset conf of the portals modules (from #4160)
- [x] Authentication sources -> Empty Acces duration is allowed (from #4151)
- [x] Switch Group doesn't contain Members tab
- [x] You can select multiple sources for the same row in the connection profile configuration. This results in a failure to save
- [x] Previously saved provisioners appear as empty in the connection profile configuration
- [x] Ordering of connection profiles is wrong (should follow the order in the config file since that order allows top to bottom matching of the profile
- [x] Editing an existing domain and going back to the listing will make the "test join" for that domain become a spinner that never ends (and there is no request to test that join)
- [x] Restarting one of the services in the interfaces doesn't provide feedback that the service is restarting other than a notification at the end. The UI should provide feedback that the service is restarting

**Missing or grammatical errors in response messages**
- [x] Integration -> Cisco Mobility Services Engine: When saving settings, it says "mse_tab updated" - needs to be prettier for users (from #4153)
- [x] Integration -> Web Services: When saving settings, it says "webservices updated" - needs to be prettier for users (from #4153)

**Styling CSS Issues**
- [x]  Left panel: Switch Groups menu and sub-menus are on same level (from #4166)
- [x] Node View -> Alignment of bottom borders is not perfect on Location tab (from #4166)

**Missing features** (for @cgx @satkunas)
- [x] Auditing -> Radius Audit Logs: Missing Export to CSV (from #4168)
- [x] Users -> Create Multiple: Multiple users creation doesn't work (see #4256) (from #4167)
- [x] Printable passwords page is missing when creating or importing multiple users (from #4167)
- [x] Node View -> Missing Rapid7 tab (from #4166)
- [x] PKI Providers -> The error is not clear when a wrong path is set on the PKI provider path (from #4160)
- [x] Authentication Sources -> htpasswd : Need to show an error when the file doesn't exist. (from #4151)
- [x] Custom reports -> 

**Issues that will be address post 9.0 (for 9.1...)**
- [x] Embedded asciidoc (from #4228)

**Comment by jrouzierinverse** [comment]
WrixLocation does not make sense it just a table for dumping data like option82

**Comment by jrouzierinverse** [comment]
There is no locality in PKI
